-- Set the PDB FREEPDB1 as the container
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Creating the SCHEMA_1 schema
BEGIN
EXECUTE IMMEDIATE 'CREATE USER SCHEMA_1 IDENTIFIED BY user_password';
EXCEPTION
WHEN OTHERS THEN
IF SQLCODE != -1918 THEN -- Ignore error if user already exists
RAISE;
END IF;
END;
/

-- Grants permissions to SCHEMA_1
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO SCHEMA_1;

-- Creation of the USER table in the SCHEMA_1 schema
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE table_name = 'USER' AND owner = 'SCHEMA_1';
IF v_count = 0 THEN
EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_1.USER (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
email VARCHAR2(100) NOT NULL
)
';
END IF;
END;
/

-- Creation of the CAR table in the SCHEMA_1 schema
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE table_name = 'CAR' AND owner = 'SCHEMA_1';
IF v_count = 0 THEN
EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_1.CAR (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
model VARCHAR2(100) NOT NULL,
year NUMBER NOT NULL,
user_id NUMBER,
CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES SCHEMA_1.USER(id)
)
';
END IF;
END;
/