ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM all_tables
    WHERE table_name = 'USER' AND owner = 'SCHEMA_1';
    IF v_count = 0 THEN

EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_1."USER" (
                                 id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                 name VARCHAR2(255),
                                 email VARCHAR2(255),
                                 CONSTRAINT USER_PK PRIMARY KEY (id)
)
';
END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM all_tables
    WHERE table_name = 'CAR' AND owner = 'SCHEMA_1';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_1.CAR (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                              entity VARCHAR2(255),
                              year NUMBER(4),
                              user_id NUMBER,
                              CONSTRAINT CAR_PK PRIMARY KEY (id),
                              CONSTRAINT CAR_USER_FK FOREIGN KEY (user_id) REFERENCES SCHEMA_1."USER"(id)
)
';
    END IF;
END;
/