#version: '3'
services:
  oracle:
    #image: gvenzl/oracle-xe
    image: gvenzl/oracle-free
    #image: -gvenzl/oracle-free:slim
    #image: -gvenzl/oracle-free:latest
    #image: -gvenzl/oracle-free:full
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 031210
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./docker/oracle/reset_password.sh:/container-entrypoint-initdb.d/reset_password.sh
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/sua_senha@//localhost:1521/FREEPDB1", "as", "sysdba", "<<<", "exit"]
      interval: 10s
      timeout: 5s
      retries: 30

  app:
    build: .
    ports:
      - "58080:58080"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 031210

volumes:
  oracle_data: