#version: '3.9'
services:
  oracle:
    image: gvenzl/oracle-free
    container_name: dev-commons-oracle-1
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 031210
      APP_USER: system
      APP_USER_PASSWORD: 031210
      TARGET_PDB: FREEPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./docker/oracle/init-oracle.sh:/container-entrypoint-initdb.d/init-oracle.sh

    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 30
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-commons-app
    ports:
      - "58080:58080"
    environment:
      SPRING_DATASOURCE_SCHEMA1_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      SPRING_DATASOURCE_SCHEMA1_USERNAME: system
      SPRING_DATASOURCE_SCHEMA1_PASSWORD: 031210
      SPRING_DATASOURCE_SCHEMA1_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_DATASOURCE_SCHEMA2_URL: jdbc:oracle:thin:@oracle:1521/FREEPDB1
      SPRING_DATASOURCE_SCHEMA2_USERNAME: system
      SPRING_DATASOURCE_SCHEMA2_PASSWORD: 031210
      SPRING_DATASOURCE_SCHEMA2_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      # As variáveis comentadas abaixo podem ser removidas se não forem mais usadas:
      #SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:FREEPDB1
      #SPRING_DATASOURCE_USERNAME: system
      #SPRING_DATASOURCE_PASSWORD: 031210
    depends_on:
      oracle:
        condition: service_healthy
volumes:
  oracle_data: