#version: '3.9'
services:
  oracle:
    image: gvenzl/oracle-free
    container_name: dev-commons-oracle-1
    #image: gvenzl/oracle-xe
    #image: -gvenzl/oracle-free:slim
    #image: -gvenzl/oracle-free:latest
    #image: -gvenzl/oracle-free:full
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 031210
      APP_USER: system
      APP_USER_PASSWORD: 031210
      TARGET_PDB: FREEPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata
      #- ./docker/oracle/reset_password.sh:/container-entrypoint-initdb.d/reset_password.sh
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/031210@//localhost:1521/FREEPDB1", "as", "sysdba", "<<<", "exit"]
      interval: 10s
      timeout: 5s
      retries: 30
      #test: ["CMD", "healthcheck.sh"]
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-commons-app
    ports:
      - "58080:58080"
    environment:
      SPRING_DATASOURCE_SCHEMA1_URL: jdbc:oracle:thin:@127.0.0.1:1521/FREEPDB1
      SPRING_DATASOURCE_SCHEMA1_USERNAME: system
      SPRING_DATASOURCE_SCHEMA1_PASSWORD: 031210
      SPRING_DATASOURCE_SCHEMA1_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_DATASOURCE_SCHEMA2_URL: jdbc:oracle:thin:@127.0.0.1:1521/FREEPDB1
      SPRING_DATASOURCE_SCHEMA2_USERNAME: system
      SPRING_DATASOURCE_SCHEMA2_PASSWORD: 031210
      SPRING_DATASOURCE_SCHEMA2_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      #SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:FREEPDB1
      #SPRING_DATASOURCE_USERNAME: system
      #SPRING_DATASOURCE_PASSWORD: 031210
    depends_on:
      oracle:
        condition: service_healthy
volumes:
  oracle_data: