ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER SCHEMA_2 IDENTIFIED BY "user_password2"
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users';
EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO SCHEMA_2';
EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO SCHEMA_2';
EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO SCHEMA_2';
EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO SCHEMA_2';

EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1920 THEN -- ORA-01920: user name 'string' conflicts with another user or role name
            RAISE;
END IF;
END;
/