-- Set the PDB FREEPDB1 as the container
ALTER SESSION SET CONTAINER = FREEPDB1;

-- Creating the SCHEMA_2 schema
BEGIN
EXECUTE IMMEDIATE 'CREATE USER SCHEMA_2 IDENTIFIED BY product_password';
EXCEPTION
WHEN OTHERS THEN
IF SQLCODE != -1918 THEN -- Ignore error if user already exists
RAISE;
END IF;
END;
/

-- Grants permissions to SCHEMA_2
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO SCHEMA_2;

-- Creation of the MARKETPLACE table in the SCHEMA_2 schema
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE table_name = 'MARKETPLACE' AND owner = 'SCHEMA_2';
IF v_count = 0 THEN
EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_2.MARKETPLACE (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
description VARCHAR2(500),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
';
END IF;
END;
/

-- Creation of the PRODUCTS table in the SCHEMA_2 schema
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count
FROM all_tables
WHERE table_name = 'PRODUCTS' AND owner = 'SCHEMA_2';
IF v_count = 0 THEN
EXECUTE IMMEDIATE '
CREATE TABLE SCHEMA_2.PRODUCTS (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR2(100) NOT NULL,
price NUMBER(10,2) NOT NULL,
marketplace_id NUMBER,
CONSTRAINT fk_marketplace FOREIGN KEY (marketplace_id) REFERENCES SCHEMA_2.MARKETPLACE(id)
)
';
END IF;
END;
/